apiVersion: apps/v1 # menggunakan api app/v1
kind: Deployment # menggunakan object deployment
metadata: 
  name: karsajobs-deployment # memberi nama pod
spec:
  replicas: 1 # menentukan replica
  selector:
    matchLabels: # menentukan label
      app: karsajobs
      type: backend 
  template:
    metadata:
      labels:
        app: karsajobs
        type: backend
    spec:
      containers:
      - name: karsajobs-backend # memberi nama container
        image: ghcr.io/hildanku/karsajobs:latest # menentukan image
        ports:
        - containerPort: 8080 # expose port
        env: # menentukan environment
          - name: APP_PORT
            value: "8080"
          - name: MONGO_HOST
            value: mongo-service
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_USERNAME
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_PASSWORD