apiVersion: v1 # menggunakan api v1
kind: Service # menggunakan object service
metadata:
  name: mongo-service # memberi nama service
spec: 
  selector: # menentukan label
    app: mongo
  ports: # expose port
  - port: 27017
    targetPort: 27017