apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
spec:
#problenya disini diNodePort
  type: NodePort
  selector:
    app: karsajobs
    type: backend
  ports:
  - port: 8080
    targetPort: 8080
